from enum import Enum

class CharnwoodCodes(Enum):
    CM01 = 'Low to High Hazard Substances (Possible carcinogens)'
    CM02 = 'Very High Hazard Substances and Special Cases (Known and probable carcinogens)'
    CM03 = 'Pyrophoric Liquids'
    CM04 = 'Water Sensitive Reagents'
    CM05 = 'Oxidising Agents'
    CM06 = 'Potential Explosive Materials'
    CM07 = 'Harmful to the Environment'
    CM08 = 'Reactive Metal Hydrides (Excluding LiAlH4)'
    CM09 = 'Hydrogenation Catalysts'
    CM010 = 'Ethers'
    CM011 = 'Phenols'
    CM012a = 'Trifluoroacetic Acid, Trifluoroacetic Anhydride, Trifluoromethanesulfonic Acid, Trifluoromethanesulfonic Anhydride, Methanesulfonic Acid, Methanesulfonic Anhydride'
    CM012b = 'Hydrogen Fluoride, Potassium Fluoride, Cesium Fluoride, Tetrabutylammonium Fluoride'
    CM013 = 'Chemical Sensitisers'
    CM014 = 'Phosphorus Oxychloride and Thionyl Chloride'
    CM015 = 'Ozone'
    CM016 = 'Phosgene (including Di- and Tri-phosgene)'
    CM017 = 'Azides'
    CM018 = 'Lithium Aluminium Hydride'
    CM019 = 'Cyanides'
    CM020 = 'Solvents'
